### ISSUE TITLE
plugin not working since update to 0.4.0

### ISSUE THREAD

**Issue by Blaimi** [sualko/cloud_piwik#56] opened 2018-04-17 11:21 UTC
the plugin is not working anymore. downgrading to 0.3.2 works.

nextcloud 13.0.1. the error-logger shows nothing. also: no admin-settings anymore like in #55.

**Comment by sualko** [comment] 2018-04-17 11:38
duplicate of #55

**Closed by sualko** 2018-04-17 11:38 UTC
