### ISSUE TITLE
I don't know if it's a bug - missing semikolon in piwik.js

### ISSUE THREAD

**Issue by olgru** [sualko/cloud_piwik#60] opened 2018-07-20 13:20 UTC
Hello.

Sorry that I didn't follow the template provided here. But I'm not sure if this is a bug and I have no idea if it can be reproduced somewhere else... In fact, I have no idea how the https sting looks like which is used to call the piwik server... Anyway:

I tried to use Piwik plugin with NC13.0.4. I’ve an external piwik server. It didn’t work. Using Firefox F12 console, I found the following error:
SyntaxError: unexpected token: identifier[Learn More] piwik.js:1:5.
This error is basically talking about a missing “;” somewhere in piwik.js. But the piwik.js code is loaded from the piwik server and for me it’s hard to believe that the error is comming from there.

I do believe that the code which creates the parameter which are then handled to piwik.js is causing this error.

Does someone have any hints/ideas on this?
I really would like to have nextcloud tracked by piwik.

Thanks,

Oliver

PS:
The installation hints for Piwik plugin are always referring to the /piwik/ folder on the piwik server, which is not the case on my system. piwik is installed in document root in a sub-domain…

**Comment by sualko** [comment] 2018-07-21 10:00
> SyntaxError: unexpected token: identifier[Learn More] piwik.js:1:5.

As the error message references the external piwik script, there is no way this is produced by this app. I suggest you look at the file (inside the web console) and maybe the server adds a error message or something similar.

> The installation hints for Piwik plugin are always referring to the /piwik/ folder on the piwik server, which is not the case on my system. piwik is installed in document root in a sub-domain…

That's right, but I think as admin you should be able to understand the intent and adjust the values by yourself. Maybe we can add an explanation like "we assume piwik is installed under `/piwik` if this differs in your installation, adjust the value accordingly". Pull requests are always welcome :wink:

**Comment by olgru** [comment] 2018-07-22 11:58
Hello.

Thanks for this quick feedback. I understood that this is for sure not an issue of the plugin. You said "no way". OK.  But I think if I handle faulty parameters specially unexpected chars for instance  to another script that this script will fail to process my parameters - because I called it wrong... But you are an expert, I'm just an old guy.

As my knowledge is limited there is nothing more I can do. I did the configuration following the limited documentation with best effort. My matomo server is https://matomo.example.de ... no subdirs, nothing. Same with the nextcloud at https://nextcloud.otherexample.de. I've seen techniques to prevent x-site scripting, I've read something about rewrite rule (which want to rewrite "/piwik/" folder - which I don't have). I think I even read people saying that you need to put "/piwik/" into the Piwik/Matomo Url -Field. In fact, I even create a symlink to provide a /piwik/ Folder on the matomo server... ;-)
However I also learnt that an admin (whatever it is) has to be able to understand someones intent by guessing.

Please take my apologies for my question.
Have a nice sunday,

Oliver

**Comment by sualko** [comment] 2018-07-23 06:42
> Please take my apologies for my question.

No need for apologies. It's a weird bug and I understand the confusion.

>  But I think if I handle faulty parameters specially unexpected chars for instance to another script that this script will fail to process my parameters

I don't understand that, but if your error occurs in ` https://matomo.example.de/piwik.js` I don't know how this can be a problem of this app.

> no subdirs, nothing

That's totally fine. I have a similar setup and it's no problem.

> I've seen techniques to prevent x-site scripting, I've read something about rewrite rule

There is CORS and SOP, but usually you should get a different kind of error.

But please follow my advice: "I suggest you look at the file (inside the web console) and maybe the server adds a error message or something similar."

I close this issue, because I think your problem is not caused by this app. Feel free to reopen it, if you find out that it is anyway the case.

**Closed by sualko** 2018-07-23 06:42 UTC
