### ISSUE TITLE
No tracking after upgrade to to 0.5.0 - 404 error for tracking.js 

### ISSUE THREAD

**Issue by brtptrs** [sualko/cloud_piwik#63] opened 2018-10-30 16:52 UTC
### Expected behavior
Page views in Nextcloud get registered in Matoma

### Actual behavior
No Tracking takes place and a 404 error gets registered for /apps/piwik/js/tracking.js

### Steps to reproduce the behavior
1. Update app to 0.5.0
2. Call any Nextclou page
3. Check results in Matona 
4. No more actions get registered
5. On the nextcloud 

### Environment
- **App version:** 0.5.0
- **Nextcloud version:** 14.0.2
- **Browser vendor and version:** Firefox 63
- **Any browser plugins enabled?** 
- **Is your Matomo installation working as expected?** Yes 

#### Javascript

```
```
![nextcloud_matomo_20181030175143](https://user-images.githubusercontent.com/8102905/47735235-6d1d1000-dc6c-11e8-8dab-c0e4dea4a9b8.png)

#### Nextcloud

```
```

**Comment by brtptrs** [comment] 2018-10-30 17:04
I have cleared all caches in Firefox and reinstalled the app after uninstalling. I also get the same behaviour an different machines. PC, Notebook and Android.

**Comment by sualko** [comment] 2018-10-30 17:35
I'm sorry that you have trouble with the latest release, but I need some more help from you. The 404 is quite unusual for Nextcloud, because normally you get a 302 if you try to access an not existing route. What happens if you try to download `/apps/piwik/js/tracking.js` directly? Is the 404 from your webserver or Nextcloud? Do you have any related log entry in your web server or NC log? If you don't use any rewriting the url should be something like `index.php/apps/piwik/...`. Do you use rewriting?

**Comment by brtptrs** [comment] 2018-10-31 08:10
Calling apps/piwik/js/tracking.js directly returns a "file not found" error.
We don't do any fancy stuff on the nextcloud installation. Nextcloud is installed in a subdirectory, that's the only slightly unusual point.

**Comment by brtptrs** [comment] 2018-10-31 08:14
Interesting is: Viewing the source code of the "page-not-found" error page does show the js code.
view-source:https://path-to-mycloud/apps/piwik/js/tracking.js

*!
 * cloud_piwik v0.5.0 - 2018-10-29
 * 
 * Copyright (c) 2018 Klaus Herberth <klaus@jsxc.org> <br>
 * Released under the MIT license
 * 
 * Please see https://github.com/sualko/cloud_piwik
 * 
 * @author Klaus Herberth <klaus@jsxc.org>
 * @version 0.5.0
 * @license MIT
 */

/* global OC */

var _paq = _paq || [];
......

**Comment by sualko** [comment] 2018-11-01 00:57
Are you sure that you don't use url rewriting? Because normally the url should look like `http://localhost/nextcloud/index.php/apps/piwik/js/tracking.js`. The `index.php` is the important part here, but anyway what I meant above was that if you request something like `http://localhost/nextcloud/index.php/apps/files404/` you get an 302 and not an 404. A 404 means the Nextcloud is not involved.

My guess is that you messed up your rewrite config. Look `overwrite.cli.url` and `htaccess.RewriteBase` in your nc config and check your server config.

Btw I tested both setups: With and without url rewriting and I can't reproduce your issue. Sorry.

**Comment by brtptrs** [comment] 2018-11-05 17:23
I just had a look at the code inside the "cloud_piwik-0.5.0.tar.gz" release, it seems the is no file called "tracking.js" in piwik/js. Only a file called "track.js". Is this correct?
On out live server there is no "tracking.js" file after an online upgrade either.

**Comment by sualko** [comment] 2018-11-06 19:57
That's right. It's using a Nextcloud route and this is also the reason why there should be an `index.php` in the path if you don't use rewriting.

**Comment by le-yak** [comment] 2019-02-10 10:36
I experienced the exact same behaviour as @brtptrs (Nextcloud v.15.0.2 / cloud_piwik v0.5.0).
I believe it has something to do with which URL are allowed by default in Nextcloud, I recall reading something like this during my investigations. Unfortunately I am unable to the reference anymore, sorry.

Changing the script's URL from `.../js/tracking.js` to `.../js/script` fixed the issue for me.

**Comment by le-yak** [comment] 2019-02-10 23:32
After further investigations, this has nothing to do with Content Security Policy, as I came to suspect a some point.
This is my `.htaccess` freshly generated by `occ maintenance:update:htaccess`:

```
  DirectoryIndex index.php index.html
(removed for brevity)
  RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
  RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff2?|ico|jpg|jpeg)$
(removed for brevity)
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /
```

Any route ending with ".js" (or any extention that appear the exclusion list) is ignored by the rewrite engine. Changing the route to anything else solves the problem.

Setup:
* Apache 2.4.34
* PHP 7.2.9
* Nextcloud 15.0.4 (yup, updated 2hrs ago)
* cloud_piwik 0.5.0
* config.php:
```
  'overwrite.cli.url' => 'https://example.com',
  'htaccess.RewriteBase' => '/',
```

_____
The weirdest thing of all is that I too receive the JS script in the HTTP response body (tested with `curl`, therefore not a browser cache thing), along with the 404 response : 

```
$ curl -v https://example.com/apps/piwik/js/tracking.js
< HTTP/1.1 404 Not Found
(...)
* cloud_piwik v0.5.0 - 2018-10-29
(...)
```

This must have something to do with the 404 being processed by `index.php` since I get an empty 404 response if I remove the `DirectoryIndex` directive.  But I'm stopping my goose chase for now...

**Comment by sualko** [comment] 2019-03-04 09:28
> The weirdest thing of all is that I too receive the JS script in the HTTP response body

Therefore I don't believe this is related to the rewrite rule. On an other app, I had a similar issue and it was related to the returned filename. Currently `tracking.js` is delivered as `script`. Maybe this is the reason why you get a 404, with the body tag, but I'm unsure. The only thing I can say, is that it is working for me with the same rewrite rules. I will update the app and it would be great if you could give me some feedback. It would also be helpful if you could send me your url to klaus@jsxc.org, so I can investigate this further.

**Comment by sualko** [comment] 2019-03-04 10:22
It would be awesome if you could test the latest release.

**Comment by brtptrs** [comment] 2019-03-05 13:44
v0.5.1 unfortunately does not solve the problem for me. 
Upgrade Steps (from NC front end):
- Deactivate
- Remove
- Download and install
I still get a 404 on 
apps/piwik/js/tracking.js

**Comment by sualko** [comment] 2019-03-06 09:25
Can you send me your url to klaus@jsxc.org?

**Comment by brtptrs** [comment] 2019-03-07 11:03
@sualko done, and thank you for the effort.

**Comment by sualko** [comment] 2019-03-28 21:58
I hope I can release a fix for this bug this weekend. Sorry for the trouble.

**Closed** 2019-03-29 12:23 UTC
