### ISSUE TITLE
Nextcloud 24 support

### ISSUE THREAD

**Issue by sunjam** [sualko/cloud_piwik#90] opened 2022-05-06 18:05 UTC
Please update for Nextcloud 24, which was released this past Monday.  I have not yet tested this update because I am on a production instance.  Perhaps someone else reading this can.  Thank you!

**Comment by kjyv** [comment] 2022-06-02 12:11
It seems to work fine (not tested extensively but event appear in Matomo) when enabling the unsupported app in NC 24. But an update would still be good

**Comment by Mannshoch** [comment] 2022-11-07 17:16
ping @sualko

**Comment by sualko** [comment] 2022-11-19 10:42
Hi everyone,
the issue is that Nextcloud deprecated the `app.php` some time ago and therefore we have to update this application to the new [application bootstrapping](https://docs.nextcloud.com/server/latest/developer_manual/app_development/bootstrap.html). I'm not even sure if it can be done anymore. At least it takes probably some hours to implement / test / research. Since I do not use this app anymore, it's pretty hard to motivate. You can help if you [buy me a coffee](https://ko-fi.com/sualko), but I can't promise anything.

**Comment by sualko** [comment] 2022-11-19 11:45
It was easier than I thought. If you like to help, please test https://github.com/sualko/cloud_piwik/releases/tag/v0.11.0-beta.1

**Comment by sualko** [comment] 2022-11-27 11:48
Fixed with https://github.com/sualko/cloud_piwik/releases/tag/v0.11.0

**Closed by sualko** 2022-11-27 11:48 UTC

**Comment by sualko** [comment] 2022-11-27 11:58
I just want to let you know that I have trouble releasing the new version in the app store. I have to contact Nextcloud to fix the issue, so it can take some time.
